### ISSUE TITLE
crash in licensed-facility-crosswalk

### ISSUE THREAD

**Issue by rkiddy** [rkiddy/ca_hhs#7]
```
licensed-facility-crosswalk
reading ids...
checking deets...
url: https://data.chhs.ca.gov/dataset/licensed-facility-crosswalk
writing...
fetching...
Archive:  licensed-facility-crosswalk-7jf3yxyn.zip
  inflating: elms-aspen-oshpd-licensed-and-certified-healthcare-facility-crosswalk.xlsx  
  inflating: elms-aspen-licensed-and-certified-healthcare-facility-crosswalk.xls  
  inflating: elms-oshpd-licensed-and-certified-healthcare-facility-crosswalk.xlsx  
  inflating: data-dictionary-licensed-and-certified-healthcare-facility-crosswalk.xls  
  inflating: lookup-table-licensed-and-certified-healthcare-facility-crosswalk.xls  
  inflating: datapackage.json        
into data...
Traceback (most recent call last):
  File "/home/ray/Projects/ca_hhs/licensed-facility-crosswalk/facilities.py", line 217, in <module>
    facility_elms_aspen()
  File "/home/ray/Projects/ca_hhs/licensed-facility-crosswalk/facilities.py", line 123, in facility_elms_aspen
    wb = excel.load_my_workbook('xlsx', f)
  File "/home/ray/Projects/ca_hhs/licensed-facility-crosswalk/excel.py", line 8, in load_my_workbook
    return load_workbook(f)
  File "/home/ray/Projects/ca_hhs/licensed-facility-crosswalk/.venv/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 346, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "/home/ray/Projects/ca_hhs/licensed-facility-crosswalk/.venv/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
  File "/home/ray/Projects/ca_hhs/licensed-facility-crosswalk/.venv/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 93, in _validate_archive
    raise InvalidFileException(msg)
openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support the old .xls file format, please use xlrd to read this file, or convert it to the more recent .xlsx file format.
```

**Comment by rkiddy** [comment]
```
start
Sun Oct 20 05:07:03 PM PDT 2024
reading ids...
checking deets...
url: https://data.chhs.ca.gov/dataset/licensed-facility-crosswalk
writing...
fetching...
Archive:  licensed-facility-crosswalk-7jf3yxyn.zip
  inflating: elms-aspen-oshpd-licensed-and-certified-healthcare-facility-crosswalk.xlsx  
  inflating: elms-aspen-licensed-and-certified-healthcare-facility-crosswalk.xls  
  inflating: elms-oshpd-licensed-and-certified-healthcare-facility-crosswalk.xlsx  
  inflating: data-dictionary-licensed-and-certified-healthcare-facility-crosswalk.xls  
  inflating: lookup-table-licensed-and-certified-healthcare-facility-crosswalk.xls  
  inflating: datapackage.json        
into data...
licensed_facility_elms_oshpd_crosswalk # 16018
licensed_facility_aspen_oshpd_crosswalk # 15037
Sun Oct 20 05:08:01 PM PDT 2024
done
```
